#!/usr/bin/python
# -*- coding: utf-8 -*-
#
#       ipm (IP Manager) is a simple tool for managing network
#       interfaces (IP addresses and routing) in GNU/Linux.
#       Home page: http://flant.ru/projects/ipm
#       
#       Copyright (C) 2009-2013 CJSC Flant (www.flant.ru)
#       Written by Dmitry Stolyarov <dmitry.stolyarov@flant.ru>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

#
# Copyright (C) 2009-2013 CJSC Flant (www.flant.ru)
# Written by Dmitry Stolyarov <dmitry.stolyarov@flant.ru>
#


import yaml, os, sys, subprocess, re, Queue, threading
from optparse import OptionParser
from lockfile import FileLock

class IPM:
  objtypes_order = ['addr', 'route']

  def __init__(self, filename):
    try:
      self.null = file('/dev/null', 'w+')
    except:
      print 'Error: Failed to open /dev/null'
      sys.exit(1)
 
    if not os.path.isfile(filename):
      print 'Error: Bad configuration file "%s": No such file' % filename
      sys.exit(1)

    with file(filename, 'r') as stream:
      try:
        self.data = yaml.load(stream)
      except yaml.YAMLError, exc:
        print ('Error: Bad configuration file "%s": Failed to parse' % filename), exc
        sys.exit(1)

    # base check
    if not isinstance(self.data, dict):
      print 'Error: Bad configuration file "%s": Bad structure' % filename
      sys.exit(1)

    # config section and state_dir param
    if not self.data.has_key('config') or not isinstance(self.data['config'], dict):
      print 'Error: Bad configuration file "%s": No "config" section' % filename
      sys.exit(1)
    if not self.data['config'].has_key('state_dir'):
      print 'Error: Bad configuration file "%s": No "state_dir" param' % filename
      sys.exit(1)
    if not os.path.isdir(self.data['config']['state_dir']):
      try:
        os.makedirs(self.data['config']['state_dir'], 0755)
      except:
        print 'Error: State dir: No such directory, mkdir failed'
        sys.exit(1)

    # check interfaces
    for dev, if_conf in self.data['interfaces'].items():
      if not isinstance(if_conf, dict):
        print 'Error: Bad configuration file "%s": Bad config for interface "%s", ignoring' % (filename, dev)
        self.data['interfaces'].pop(dev)
        continue

      if len(if_conf) <= 0:
        self.data['interfaces'].pop(dev)
        continue

      for objtype, items in if_conf.items():
        if items == None:
          self.data['interfaces'][dev].pop(objtype)
          continue
        if not isinstance(items, list):
          print 'Error: Bad configuration file "%s": Bad config for interface "%s": Bad config for objtype "%s", ignoring' % (filename, dev, objtype)
          self.data['interfaces'][dev].pop(objtype)
          continue

        for item in items:
          if not isinstance(item, str):
            print 'Error: Bad configuration file "%s": Bad config for interface "%s": Bad config for objtype "%s": One item is bad, ignoring' % (filename, dev, objtype)
            self.data['interfaces'][dev][objtype].remove(item)
            continue
          if objtype == 'addr' and self._extract_addr(item) == False:
            print 'Error: Bad configuration file "%s": Bad config for interface "%s": Bad config for objtype "%s": Failed to extract addr from item "%s", ignoring' % (filename, dev, objtype, item)
            self.data['interfaces'][dev][objtype].remove(item)
            continue

    # file lock
    if not os.path.isdir(self.data['config']['state_dir'] + '/.lock'):
      try:
        os.makedirs(self.data['config']['state_dir'] + '/.lock', 0755)
      except:
        print 'Error: Failed to create lock dir %s' % self.data['config']['state_dir'] + '/.lock'
        sys.exit(1)
    self.filelock = FileLock(self.data['config']['state_dir'] + '/.lock/ipm')

    # threading
    self.thlocal = threading.local()
    if not self.data['config'].has_key('concurrency'):
      self.concurrency = 1
    else:
      self.concurrency = self.data['config']['concurrency']

  def up(self, dev):
    if os.path.isfile(self._if_state_filename(dev)):
      return True, ''

    buf = self._buffer()

    print >> buf, 'Configuring interface %s:' % dev

    if_conf = self._if_conf(dev)
    if not if_conf:
      print >> buf, ' = Error: No such interface (in configuration file)'
      return False, buf.data()

    r, ok_objtypes = self._do(dev, 'add', if_conf)

    if r:
      with file(self._if_state_filename(dev), 'w') as stream:
        yaml.dump(if_conf, stream)
    else:
      if_state = {}
      for objtype, items in ok_objtypes:
        if_state[objtype] = []
        for item in items:
          if_state[objtype].append(item)
        if not len(if_state[objtype]):
          if_state.pop(objtype)
        if len(if_state):
          with file(self._if_state_filename(dev), 'w') as stream:
            yaml.dump(if_state, stream)

    print >> buf, ' = %s' % ('Done' if r else 'Failed')

    return r, buf.data()

  def down(self, dev):
    if_state = self._if_state(dev)
    if not if_state: return True, ''

    buf = self._buffer()

    print >> buf, 'Deconfiguring interface %s:' % dev

    r, ok_objtypes = self._do(dev, 'delete', if_state)
 
    if r:
      os.unlink(self._if_state_filename(dev))
    else:
      for objtype, items in ok_objtypes:
        for item in items:
          if_state[objtype].remove(item)
        if not len(if_state[objtype]):
          if_state.pop(objtype)
      with file(self._if_state_filename(dev), 'w') as stream:
        yaml.dump(if_state, stream)

    print >> buf, ' = %s' % ('Done' if r else 'Failed')

    return r, buf.data()

  def reload(self, dev):
    r, bufdata = self.down(dev)
    if r:
      up_res = self.up(dev)
      r = r and up_res[0]
      bufdata = bufdata + up_res[1]
    return r, bufdata

  def update(self, dev):
    buf = self._buffer()

    print >> buf, 'Updating interface %s:' % dev,
    has_to_delete = has_to_add = False

    if_state = self._if_state(dev)
    if not if_state: if_state = {}

    if_conf = self._if_conf(dev)
    if not if_conf:
      if not len(if_state):
        print >> buf
        print >> buf, ' = Error: No such interface (both in configuration and in state)'
        return False, buf.data()
      if_conf = {}

    # delete old routes
    # delete old addr
    if_tmp = {}
    for objtype, items in if_state.items():
      if_tmp[objtype] = []
      for item in items:
        if if_conf.has_key(objtype) and if_conf[objtype].count(item): continue
        if_tmp[objtype].append(item)
        has_to_delete = True
    
    if has_to_delete: print >> buf

    r_delete, ok_objtypes = self._do(dev, 'delete', if_tmp)
    for objtype, items in ok_objtypes:
      for item in items:
        if_state[objtype].remove(item)
      if not len(if_state[objtype]):
        if_state.pop(objtype)

    # add new rotutes
    # add new addr
    if_tmp = {}
    for objtype, items in if_conf.items():
      if_tmp[objtype] = []
      for item in items:
        if if_state.has_key(objtype) and if_state[objtype].count(item): continue
        if_tmp[objtype].append(item)
        has_to_add = True
    if not has_to_delete and has_to_add: print >> buf
    r_add, ok_objtypes = self._do(dev, 'add', if_tmp)
    for objtype, items in ok_objtypes:
      if not if_state.has_key(objtype):
        if_state[objtype] = []
      for item in items:
        if_state[objtype].append(item)
      if not len(if_state[objtype]):
        if_state.pop(objtype)

    if len(if_state) > 0:
      with file(self._if_state_filename(dev), 'w') as stream:
        yaml.dump(if_state, stream)
    else:
      if os.path.isfile(self._if_state_filename(dev)):
        os.unlink(self._if_state_filename(dev))

    if has_to_add or has_to_delete:
      print >> buf, ' = %s' % ('Done' if r_add and r_delete else 'Failed')
    else:
      print >> buf, 'No changes'

    return r_add and r_delete, buf.data()

  def status(self, dev):
    buf = self._buffer()

    print >> buf, '%s:' % dev

    if_state = self._if_state(dev)
    if not if_state:
      print >> buf, ' = Error: Interface is not up!'
      return False, buf.data()

    r = True
    for objtype, items in if_state.items():
      for item in items:
        lr = self._do_status(dev, objtype, item)
        if not lr: r = False
        print >> buf, ' * %s %s: %s' % (objtype, item, 'Ok' if lr else 'Bad')
    print >> buf, ' = %s' % ('Ok' if r else 'Bad')

    return r, buf.data()

  def zap(self, dev):
    if os.path.isfile(self._if_state_filename(dev)):
      return os.unlink(self._if_state_filename(dev)), ''
    return True, ''

  def up_all(self):
    tm = IMP_Taskman(self.concurrency)

    tm.start()
    for dev in self._list_in_conf():
      tm.add_task(self.up, (dev))
    results = tm.get_results()

    r = True
    bufdata = ''
    for result in results:
      r = r and result[0]
      bufdata = bufdata + result[1]

    tm.stop()

    return r, bufdata


  def down_all(self):
    tm = IMP_Taskman(self.concurrency)

    tm.start()
    for dev in self._list_configured():
      tm.add_task(self.down, (dev))
    results = tm.get_results()

    r = True
    bufdata = ''
    for result in results:
      r = r and result[0]
      bufdata = bufdata + result[1]

    tm.stop()

    return r, bufdata


  def reload_all(self):
    tm = IMP_Taskman(self.concurrency)

    tm.start()
    for dev in self._list_configured():
      tm.add_task(self.reload, (dev))
    results = tm.get_results()

    r = True
    bufdata = ''
    for result in results:
      r = r and result[0]
      bufdata = bufdata + result[1]

    tm.stop()

    up_all_res = self.up_all()
    r = r and up_all_res[0]
    bufdata = bufdata + up_all_res[1]

    return r, bufdata


  def update_all(self):
    tm = IMP_Taskman(self.concurrency)

    tm.start()
    for dev in self._list_all():
      tm.add_task(self.update, (dev))
    results = tm.get_results()

    r = True
    bufdata = ''
    for result in results:
      r = r and result[0]
      bufdata = bufdata + result[1]

    tm.stop()

    return r, bufdata


  def status_all(self):
    tm = IMP_Taskman(self.concurrency)

    tm.start()
    for dev in self._list_configured():
      tm.add_task(self.status, dev)
    results = tm.get_results()

    r = True
    bufdata = ''
    for result in results:
      r = r and result[0]
      bufdata = bufdata + result[1]

    tm.stop()

    return r, bufdata

  def zap_all(self):
    r = True
    for dev in self._list_configured():
      if not self.zap(dev)[0]: r = False
    return r, ''

  def _if_state_filename(self, dev):
    return self.data['config']['state_dir'] + '/' + dev

  def _if_conf(self, dev):
    if dev in self.data['interfaces']:
      return self.data['interfaces'][dev]
    return None

  def _if_state(self, dev):
    buf = self._buffer()

    if not os.path.isfile(self._if_state_filename(dev)): return False
    with file(self._if_state_filename(dev), 'r') as stream:
      try:
        if_state = yaml.load(stream)
      except:
        print >> buf, 'Error: Bad state file "%s", removing' % self._if_state_filename(dev)
        os.unlink(self._if_state_filename(dev))
        return False

    if not isinstance(if_state, dict) or len(if_state) <= 0:
      os.unlink(self._if_state_filename(dev))
      if_state = False

    return if_state

  def _do(self, dev, action, if_conf):
    r = True
    ok_objtypes = []
    for objtype in self.__class__.objtypes_order if action == 'add' else reversed(self.__class__.objtypes_order):
      if objtype not in if_conf: continue
      lr, ok_items = self._do_one(dev, action, objtype, if_conf[objtype] if action == 'add' else reversed(if_conf[objtype]))
      if not lr: r = False
      ok_objtypes.append((objtype, ok_items))
    return r, ok_objtypes

  def _do_one(self, dev, action, objtype, items):
    # action = add or delete
    # objtype = addr or route

    buf = self._buffer()

    r = True
    ok_items = []
    for item in items:
      # check status before
      precheck = True
      if action == 'add' and self._do_status(dev, objtype, item) == True:
        precheck = False
        lr = False
      elif action == 'delete' and self._do_status(dev, objtype, item) == False:
        ok_items.append(item)
        precheck = False
        lr = True

      # do-do-do!
      if precheck:
        command = '/sbin/ip %s %s dev %s %s' % (objtype, action, dev, item)
        lr = not subprocess.call(command, shell=True, stdin=self.null, stdout=self.null, stderr=self.null)
        if lr and action == 'add' and objtype == 'addr':
          lr = lr and not subprocess.call('/usr/bin/arping -c 1 -U -I %s %s' % (dev, self._extract_addr(item)), shell=True, stdin=self.null, stdout=self.null, stderr=self.null)

      # check status after
      if lr:
        if action == 'add' and self._do_status(dev, objtype, item) == False:
          command = '/sbin/ip %s %s dev %s %s' % (objtype, self._antiaction(action), dev, item)
          subprocess.call(command, shell=True, stdin=self.null, stdout=self.null, stderr=self.null)
          lr = False
        elif action == 'delete' and self._do_status(dev, objtype, item) == True:
          lr = False

      if lr:
       if precheck: tr = 'Done'
       if not precheck: tr = 'Ignored'
      else: tr = 'Failed'
      print >> buf, ' * %s %s %s: %s' % (action, objtype, item, tr)

      if not lr: r = False
      else: ok_items.append(item)

    return r, ok_items

  def _antiaction(self, action):
    if action == 'add': return 'delete'
    elif action == 'delete': return 'add'
    return False

  def _do_status(self, dev, objtype, item):
    if objtype == 'route':
      return self._status_route(dev, item)
    elif objtype == 'addr': 
      return self._status_addr(dev, item);
    else:
      return False

  def _status_route(self, dev, item):
    command = '/usr/bin/test `/sbin/ip route show dev %s %s | /usr/bin/wc -l` -eq 1' % (dev, item)
    return not subprocess.call(command, shell=True, stdin=self.null, stdout=self.null, stderr=self.null)

  def _status_addr(self, dev, item):
    command = '/usr/bin/test `/sbin/ip addr show dev %s | grep \'%s/\' | /usr/bin/wc -l` -eq 1' %  (dev, self._extract_addr(item))
    return not subprocess.call(command, shell=True, stdin=self.null, stdout=self.null, stderr=self.null)

  def _list_in_conf(self):
    devs = self.data['interfaces'].keys()
    devs.sort()
    return devs

  def _list_configured(self):
    devs = os.listdir(self.data['config']['state_dir']) 
    devs.sort()
    devs.remove('.lock')
    return devs

  def _list_all(self):
    devs = list(set(os.listdir(self.data['config']['state_dir']) + self.data['interfaces'].keys()))
    devs.sort()
    devs.remove('.lock')
    return devs

  def _extract_addr(self, string):
    addrs = []
    for word, addr in re.findall('(^ ?|\w+ )([\d]{1,3}\.[\d]{1,3}\.[\d]{1,3}\.[\d]{1,3})', string):
      word = word.strip()
      if word in ['broadcast', 'brd', 'bcast', 'anycast', 'peer']: continue
      addrs.append(addr)
    if len(addrs) != 1: return False
    return addrs.pop()

  class Buf:
    def __init__(self, thlocal, clear = False):
      self.thlocal = thlocal
      if 'bufdata' not in dir(self.thlocal):
        self.thlocal.bufdata = ''

    def write(self, s):
      self.thlocal.bufdata = self.thlocal.bufdata + s

    def data(self):
      d = self.thlocal.bufdata
      self.thlocal.bufdata = ''
      return d

  def _buffer(self):
    return IPM.Buf(self.thlocal)


class IMP_Taskman:
  def __init__(self, concurrency, threading_local = None):
    self.concurrency = concurrency

    if threading_local is None:
      threading_local = threading.local()
    self.thlocal = threading_local

    self.stopped = True
    self.cond = threading.Condition()

    self.tasks = []
    self.results = []
    self.unfinished = 0
    self.all_tasks_done = threading.Event()
    self.all_tasks_done.set()

    self.threads = []

  def start(self):
    with self.cond:
      self.stopped = False
      for _ in range(0, self.concurrency):
        thread = threading.Thread(target = self._worker)
        thread.daemon = True
        thread.start()
        self.threads.append(thread)

  def _worker(self):
    with self.cond:
      while not self.stopped:
        if len(self.tasks) == 0:
          self.cond.wait()

        if len(self.tasks) == 0: continue
        if self.stopped: break

        task, args = self.tasks.pop()

        try:
          self.cond.release()
          result = task(args)
        except:
          self.cond.acquire()
          self.unfinished = self.unfinished - 1
          if self.unfinished == 0: self.all_tasks_done.set()
          raise

        self.cond.acquire()
        self.results.append(result)
        self.unfinished = self.unfinished - 1
        if self.unfinished == 0: self.all_tasks_done.set()

  def add_task(self, task, args = ()):
    with self.cond:
      self.tasks.append((task, args))
      self.unfinished = self.unfinished + 1
      self.all_tasks_done.clear()
      self.cond.notify()

  def get_results(self):
    self.all_tasks_done.wait()
    with self.cond:
      return list(self.results)

  def stop(self):
    self.all_tasks_done.wait()

    with self.cond:
      self.stopped = True
      self.cond.notify_all()

    for thread in self.threads:
      thread.join()
    self.threads = []


def print_help():
  print """Usage: ipm [-c CONFIG] ACTION [IF | --all]

ipm is a simple tool for managing network interfaces
in GNU/Linux.

Perform an action for one interface:
 ipm [-c CONFIG] ACTION IF
 ipm [-c CONFIG] IF ACTION
  
Perform an action for all interfaces:
 ipm [-c CONFIG] ACTION --all

Show status for one or all interfaces:
 ipm [-c CONFIG] IF
 ipm [-c CONFIG] --all

IF: NIC interface name (eth0, valn5, ...)

ACTIONs: up, down, reload, update, status, zap

CONFIG:
 full path to configuration file OR
 file in /etc/ipm (with or without extension)


Home page: http://flant.ru/projects/ipm
GitHub: https://github.com/flant/ipm
"""

actions = ['up', 'down', 'reload', 'update', 'status', 'zap']
parser = OptionParser(add_help_option = False, usage = 'ipm [-c CONFIG] ACTION [IF | --all]')
parser.print_help = print_help
parser.add_option('--help', action = 'help')
parser.add_option('--all', action = 'store_true', default = False)
parser.add_option('-c', '--config', default='main')

options, args = parser.parse_args()

if os.geteuid() != 0: parser.error('you should be root to run this program')

if options.all:
  if len(args) == 0: parser.error('no action given')
  elif len(args) > 1: parser.error('to many args')
  action = args[0]
  if not action in actions: parser.error('unknown action')  
else:
  if len(args) < 2: parser.error('no action and/or interface given')
  elif len(args) > 2: parser.error('to many args')
  action, dev = args[0], args[1]
  if dev in actions: action, dev = dev, action
  if not action in actions: parser.error('unknown action')

if os.path.isfile(options.config):
  conf = options.config
elif os.path.isfile(options.config + '.yaml'):
  conf = options.config + '.yaml'
elif os.path.isfile('/etc/ipm/' + options.config):
  conf = '/etc/ipm/' + options.config
elif os.path.isfile('/etc/ipm/' + options.config + '.yaml'):
  conf = '/etc/ipm/' + options.config + '.yaml'
else:
  parser.error('no such config')

ipm = IPM(conf)

with ipm.filelock:
  if options.all:
    if action == 'up': r, bufdata = ipm.up_all()
    elif action == 'down': r, bufdata = ipm.down_all()
    elif action == 'reload': r, bufdata = ipm.reload_all()
    elif action == 'update': r, bufdata = ipm.update_all()
    elif action == 'status': r, bufdata = ipm.status_all()
    elif action == 'zap': r, bufdata = ipm.zap_all()
  else:
    if action == 'up': r, bufdata = ipm.up(dev)
    elif action == 'down': r, bufdata = ipm.down(dev)
    elif action == 'reload': r, bufdata = ipm.reload(dev)
    elif action == 'update': r, bufdata = ipm.update(dev)
    elif action == 'status': r, bufdata = ipm.status(dev)
    elif action == 'zap': r, bufdata = ipm.zap(dev)

bufdata = bufdata.strip()
if len(bufdata):
  print bufdata
  print

if r:
  print 'Command result: Success'
else:
  print 'Command result: Fail'

sys.exit(not r)
